language: python
cache: pip

python:
  - 3.6

notifications:
  email: false

git:
  depth: 1

branches:
  except:
    - travis-artifacts

matrix:
  fast_finish: true
  allow_failures:
    - env: ACTION=shellcheck

env:
  matrix:
    - ACTION=pkgcheck
    - ACTION=shellcheck

before_cache:
    - rm -v -f ${HOME}/.cache/pip/log/debug.log

install:
  - pip install jinja2 lxml pkgcheck pyyaml

before_script:
  - sudo mkdir -p /etc/portage /var/cache/distfiles /var/db/repos/gentoo /var/db/repos/graaff
  - sudo chmod a+rwX /etc/portage /var/cache/distfiles /var/db/repos/gentoo /var/db/repos/graaff
  - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
  - curl -s "https://codeload.github.com/gentoo-mirror/gentoo/tar.gz/master" | tar xz -C /var/db/repos/gentoo --strip-components=1
  - curl -s "https://codeload.github.com/gentoo-mirror/graaff/tar.gz/master" | tar xz -C /var/db/repos/graaff --strip-components=1
  - cp .travis/myrepos.conf /etc/portage/repos.conf

script:
  - .travis/script.sh $ACTION

before_deploy:
  - pip install "https://codeload.github.com/gentoo/portage/tar.gz/master"
  - python3 .travis/genlist.py

deploy:
  - provider: pages
    edge: true
    keep_history: false
    target_branch: travis-artifacts
    token: $GITHUB_TOKEN
    on:
      branch: master
      condition: $ACTION = pkgcheck
